//! Reference tests for Compare1 and Compare2.
//!
//! These tests validate the Rust implementation against the cross-language
//! test data generated by the C# TestGenerator.

use float_cmp::approx_eq;
use pragmastat::assumptions::EstimatorError;
use pragmastat::compare::{
    compare1, compare1_with_seed, compare2, compare2_with_seed, ComparisonVerdict, Metric,
    Projection, Threshold,
};
use pragmastat::measurement::Measurement;
use pragmastat::measurement_unit::MeasurementUnit;
use pragmastat::sample::Sample;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize, Serialize)]
struct ExpectedError {
    id: String,
    subject: String,
}

#[derive(Debug, Deserialize)]
struct ThresholdInput {
    metric: String,
    value: f64,
    misrate: f64,
}

#[derive(Debug, Deserialize)]
struct Compare1Input {
    x: Vec<f64>,
    #[serde(default)]
    seed: Option<String>,
    thresholds: Vec<ThresholdInput>,
}

#[derive(Debug, Deserialize)]
struct ProjectionOutput {
    estimate: f64,
    lower: f64,
    upper: f64,
    verdict: String,
}

#[derive(Debug, Deserialize)]
struct Compare1Output {
    projections: Vec<ProjectionOutput>,
}

#[derive(Debug, Deserialize)]
struct Compare1TestCase {
    input: Compare1Input,
    #[serde(default)]
    output: Option<Compare1Output>,
    #[serde(default)]
    expected_error: Option<ExpectedError>,
}

#[derive(Debug, Deserialize)]
struct Compare2Input {
    x: Vec<f64>,
    y: Vec<f64>,
    #[serde(default)]
    seed: Option<String>,
    thresholds: Vec<ThresholdInput>,
}

#[derive(Debug, Deserialize)]
struct Compare2Output {
    projections: Vec<ProjectionOutput>,
}

#[derive(Debug, Deserialize)]
struct Compare2TestCase {
    input: Compare2Input,
    #[serde(default)]
    output: Option<Compare2Output>,
    #[serde(default)]
    expected_error: Option<ExpectedError>,
}

fn find_repo_root() -> PathBuf {
    let mut current_dir = std::env::current_dir().unwrap();
    loop {
        if current_dir.join("CITATION.cff").exists() {
            return current_dir;
        }
        if !current_dir.pop() {
            panic!("Could not find repository root (CITATION.cff not found)");
        }
    }
}

fn parse_metric(s: &str) -> Metric {
    match s.to_lowercase().as_str() {
        "center" => Metric::Center,
        "spread" => Metric::Spread,
        "shift" => Metric::Shift,
        "ratio" => Metric::Ratio,
        "disparity" => Metric::Disparity,
        _ => panic!("Unknown metric: {}", s),
    }
}

fn parse_verdict(s: &str) -> ComparisonVerdict {
    match s.to_lowercase().as_str() {
        "less" => ComparisonVerdict::Less,
        "greater" => ComparisonVerdict::Greater,
        "inconclusive" => ComparisonVerdict::Inconclusive,
        _ => panic!("Unknown verdict: {}", s),
    }
}

fn verify_error(
    failures: &mut Vec<String>,
    file_name: &std::ffi::OsStr,
    err: &EstimatorError,
    expected: &ExpectedError,
    is_sample_creation: bool,
) {
    match err {
        EstimatorError::Assumption(ae) => {
            let violation = ae.violation();
            if violation.id.as_str() != expected.id {
                failures.push(format!(
                    "{file_name:?}: expected violation id \"{}\", got \"{}\"",
                    expected.id,
                    violation.id.as_str()
                ));
            }
            // Sample::new always uses Subject::X, so when the expected subject is "y"
            // and the error originates from sample construction, the subject check would
            // always fail. Skip it in that case only.
            let skip_subject = is_sample_creation && expected.subject == "y";
            if !skip_subject && violation.subject.as_str() != expected.subject {
                failures.push(format!(
                    "{file_name:?}: expected violation subject \"{}\", got \"{}\"",
                    expected.subject,
                    violation.subject.as_str()
                ));
            }
        }
        _ => {
            let err_str = err.to_string();
            if expected.id == "validity"
                && (err_str.contains("empty") || err_str.contains("validity"))
            {
                return;
            }
        }
    }
}

fn threshold_from_input(input: &ThresholdInput) -> Threshold {
    let metric = parse_metric(&input.metric);
    Threshold::new(metric, Measurement::number(input.value), input.misrate)
        .expect("Failed to create threshold")
}

fn run_compare1_tests() {
    let repo_root = find_repo_root();
    let test_data_dir = repo_root.join("tests").join("compare1");

    if !test_data_dir.exists() {
        panic!("Test data directory not found: {:?}", test_data_dir);
    }

    let json_files: Vec<_> = fs::read_dir(&test_data_dir)
        .unwrap()
        .filter_map(|entry| {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.extension()?.to_str()? == "json" {
                Some(path)
            } else {
                None
            }
        })
        .collect();

    assert!(
        !json_files.is_empty(),
        "No JSON test files found in {:?}",
        test_data_dir
    );

    let mut failures = Vec::new();

    for json_file in &json_files {
        let content = fs::read_to_string(json_file).unwrap();
        let test_case: Compare1TestCase = serde_json::from_str(&content).unwrap();
        let file_name = json_file.file_name().unwrap();

        let thresholds: Vec<Threshold> = test_case
            .input
            .thresholds
            .iter()
            .map(threshold_from_input)
            .collect();

        let x = match Sample::new(test_case.input.x.clone()) {
            Ok(s) => s,
            Err(e) => {
                if let Some(ref expected_error) = test_case.expected_error {
                    verify_error(&mut failures, file_name, &e, expected_error, true);
                } else {
                    failures.push(format!(
                        "{file_name:?}: unexpected error creating sample: {e:?}"
                    ));
                }
                continue;
            }
        };

        if let Some(ref expected_error) = test_case.expected_error {
            let result = if let Some(ref seed) = test_case.input.seed {
                compare1_with_seed(&x, &thresholds, seed)
            } else {
                compare1(&x, &thresholds)
            };
            match result {
                Ok(_) => failures.push(format!("{file_name:?}: expected error, got Ok")),
                Err(err) => {
                    verify_error(&mut failures, file_name, &err, expected_error, false);
                }
            }
            continue;
        }

        let actual_output = match if let Some(ref seed) = test_case.input.seed {
            compare1_with_seed(&x, &thresholds, seed)
        } else {
            compare1(&x, &thresholds)
        } {
            Ok(val) => val,
            Err(e) => {
                failures.push(format!("{file_name:?}: unexpected error {e:?}"));
                continue;
            }
        };

        let expected_output = test_case.output.expect("Test case must have output");

        if actual_output.len() != expected_output.projections.len() {
            failures.push(format!(
                "{file_name:?}: expected {} projections, got {}",
                expected_output.projections.len(),
                actual_output.len()
            ));
            continue;
        }

        for (i, (actual, expected)) in actual_output
            .iter()
            .zip(expected_output.projections.iter())
            .enumerate()
        {
            if !approx_eq!(
                f64,
                actual.estimate().value,
                expected.estimate,
                epsilon = 1e-9
            ) {
                failures.push(format!(
                    "{file_name:?}[{}]: expected estimate {}, got {}",
                    i,
                    expected.estimate,
                    actual.estimate().value
                ));
            }
            if !approx_eq!(f64, actual.bounds().lower, expected.lower, epsilon = 1e-9) {
                failures.push(format!(
                    "{file_name:?}[{}]: expected lower {}, got {}",
                    i,
                    expected.lower,
                    actual.bounds().lower
                ));
            }
            if !approx_eq!(f64, actual.bounds().upper, expected.upper, epsilon = 1e-9) {
                failures.push(format!(
                    "{file_name:?}[{}]: expected upper {}, got {}",
                    i,
                    expected.upper,
                    actual.bounds().upper
                ));
            }
            let expected_verdict = parse_verdict(&expected.verdict);
            if actual.verdict() != expected_verdict {
                failures.push(format!(
                    "{file_name:?}[{}]: expected verdict {:?}, got {:?}",
                    i,
                    expected_verdict,
                    actual.verdict()
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "Failed tests:\n{}",
        failures.join("\n")
    );
}

fn run_compare2_tests() {
    let repo_root = find_repo_root();
    let test_data_dir = repo_root.join("tests").join("compare2");

    if !test_data_dir.exists() {
        panic!("Test data directory not found: {:?}", test_data_dir);
    }

    let json_files: Vec<_> = fs::read_dir(&test_data_dir)
        .unwrap()
        .filter_map(|entry| {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.extension()?.to_str()? == "json" {
                Some(path)
            } else {
                None
            }
        })
        .collect();

    assert!(
        !json_files.is_empty(),
        "No JSON test files found in {:?}",
        test_data_dir
    );

    let mut failures = Vec::new();

    for json_file in &json_files {
        let content = fs::read_to_string(json_file).unwrap();
        let test_case: Compare2TestCase = serde_json::from_str(&content).unwrap();
        let file_name = json_file.file_name().unwrap();

        let thresholds: Vec<Threshold> = test_case
            .input
            .thresholds
            .iter()
            .map(threshold_from_input)
            .collect();

        let x = match Sample::new(test_case.input.x.clone()) {
            Ok(s) => s,
            Err(e) => {
                if let Some(ref expected_error) = test_case.expected_error {
                    verify_error(&mut failures, file_name, &e, expected_error, true);
                } else {
                    failures.push(format!(
                        "{file_name:?}: unexpected error creating sample x: {e:?}"
                    ));
                }
                continue;
            }
        };

        let y = match Sample::new(test_case.input.y.clone()) {
            Ok(s) => s,
            Err(e) => {
                if let Some(ref expected_error) = test_case.expected_error {
                    // true for is_sample_creation - subject check will be skipped
                    verify_error(&mut failures, file_name, &e, expected_error, true);
                } else {
                    failures.push(format!(
                        "{file_name:?}: unexpected error creating sample y: {e:?}"
                    ));
                }
                continue;
            }
        };

        if let Some(ref expected_error) = test_case.expected_error {
            let result = if let Some(ref seed) = test_case.input.seed {
                compare2_with_seed(&x, &y, &thresholds, seed)
            } else {
                compare2(&x, &y, &thresholds)
            };
            match result {
                Ok(_) => failures.push(format!("{file_name:?}: expected error, got Ok")),
                Err(err) => {
                    verify_error(&mut failures, file_name, &err, expected_error, false);
                }
            }
            continue;
        }

        let actual_output = match if let Some(ref seed) = test_case.input.seed {
            compare2_with_seed(&x, &y, &thresholds, seed)
        } else {
            compare2(&x, &y, &thresholds)
        } {
            Ok(val) => val,
            Err(e) => {
                failures.push(format!("{file_name:?}: unexpected error {e:?}"));
                continue;
            }
        };

        let expected_output = test_case.output.expect("Test case must have output");

        if actual_output.len() != expected_output.projections.len() {
            failures.push(format!(
                "{file_name:?}: expected {} projections, got {}",
                expected_output.projections.len(),
                actual_output.len()
            ));
            continue;
        }

        for (i, (actual, expected)) in actual_output
            .iter()
            .zip(expected_output.projections.iter())
            .enumerate()
        {
            if !approx_eq!(
                f64,
                actual.estimate().value,
                expected.estimate,
                epsilon = 1e-9
            ) {
                failures.push(format!(
                    "{file_name:?}[{}]: expected estimate {}, got {}",
                    i,
                    expected.estimate,
                    actual.estimate().value
                ));
            }
            if !approx_eq!(f64, actual.bounds().lower, expected.lower, epsilon = 1e-9) {
                failures.push(format!(
                    "{file_name:?}[{}]: expected lower {}, got {}",
                    i,
                    expected.lower,
                    actual.bounds().lower
                ));
            }
            if !approx_eq!(f64, actual.bounds().upper, expected.upper, epsilon = 1e-9) {
                failures.push(format!(
                    "{file_name:?}[{}]: expected upper {}, got {}",
                    i,
                    expected.upper,
                    actual.bounds().upper
                ));
            }
            let expected_verdict = parse_verdict(&expected.verdict);
            if actual.verdict() != expected_verdict {
                failures.push(format!(
                    "{file_name:?}[{}]: expected verdict {:?}, got {:?}",
                    i,
                    expected_verdict,
                    actual.verdict()
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "Failed tests:\n{}",
        failures.join("\n")
    );
}

#[test]
fn test_compare1() {
    run_compare1_tests();
}

#[test]
fn test_compare2() {
    run_compare2_tests();
}
