//! Generate static Typst width-convergence tables from sim/bounds-width.json.
//!
//! Produces one `*-width-table.typ` per bounds function.
//! These are included by the corresponding `*-notes.typ` files.

use anyhow::Result;
use serde::Deserialize;
use std::path::Path;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Row {
    n: usize,
    center_bounds: Option<f64>,
    spread_bounds: Option<f64>,
    shift_bounds: Option<f64>,
    ratio_bounds: Option<f64>,
    disparity_bounds: Option<f64>,
}

const TABLE_NS: &[usize] = &[
    2, 3, 4, 5, 10, 20, 30, 40, 50, 100, 200, 300, 400, 500, 1000, 10000,
];

struct Spec {
    output: &'static str,
    get: fn(&Row) -> Option<f64>,
}

const SPECS: &[Spec] = &[
    Spec {
        output: "manual/center-bounds/center-bounds-width-table.typ",
        get: |r| r.center_bounds,
    },
    Spec {
        output: "manual/spread-bounds/spread-bounds-width-table.typ",
        get: |r| r.spread_bounds,
    },
    Spec {
        output: "manual/shift-bounds/shift-bounds-width-table.typ",
        get: |r| r.shift_bounds,
    },
    Spec {
        output: "manual/ratio-bounds/ratio-bounds-width-table.typ",
        get: |r| r.ratio_bounds,
    },
    Spec {
        output: "manual/disparity-bounds/disparity-bounds-width-table.typ",
        get: |r| r.disparity_bounds,
    },
];

pub fn generated_paths() -> impl Iterator<Item = &'static str> {
    SPECS.iter().map(|s| s.output)
}

pub fn generate(base_path: &Path) -> Result<()> {
    let json_path = base_path.join("sim/bounds-width.json");
    let json_data = std::fs::read_to_string(&json_path)
        .map_err(|e| anyhow::anyhow!("Cannot read {}: {e}", json_path.display()))?;
    let all_rows: Vec<Row> = serde_json::from_str(&json_data)?;

    let by_n: std::collections::HashMap<usize, &Row> =
        all_rows.iter().map(|r| (r.n, r)).collect();

    for spec in SPECS {
        let content = build_table(&by_n, spec.get);
        let path = base_path.join(spec.output);
        std::fs::write(&path, content)?;
        println!("  Generated: {}", spec.output);
    }

    Ok(())
}

fn build_table(
    by_n: &std::collections::HashMap<usize, &Row>,
    get: fn(&Row) -> Option<f64>,
) -> String {
    let mut lines: Vec<String> = vec![
        "// Auto-generated by `mise run docs:sync`. Do not edit manually.".into(),
        "#table(".into(),
        "  columns: 2,".into(),
        "  stroke: none,".into(),
        "  table.hline(),".into(),
        "  [*N*], [*Width*],".into(),
        "  table.hline(),".into(),
    ];

    for &n in TABLE_NS {
        let w_str = by_n
            .get(&n)
            .and_then(|r| get(r))
            .map_or_else(|| "—".to_string(), |v| format!("{v:.4}"));
        lines.push(format!("  [{n}], [{w_str}],"));
    }

    lines.push("  table.hline(),".into());
    lines.push(")".into());
    lines.join("\n") + "\n"
}
