name: build-img

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.0'

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: img
        extra-packages: |
          any::ggplot2
          any::jsonlite
          any::dplyr
          any::tidyr
          any::latex2exp

    - name: Generate images
      run: ./img/build.sh

    - name: Upload image artifacts
      uses: actions/upload-artifact@v4
      with:
        name: img
        path: img/
