name: build-r

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.0'

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: r/pragmastat
        extra-packages: |
          any::devtools

    - name: Copy reference test data
      run: cp -r ./tests ./r/pragmastat/tests/tests

    - name: Check
      run: R -e "devtools::check()"
      working-directory: r/pragmastat

    - name: Test
      run: R -e "devtools::test()"
      working-directory: r/pragmastat

    - name: Build
      run: R -e "devtools::build()"
      working-directory: r/pragmastat

    - name: Upload r artifacts
      uses: actions/upload-artifact@v4
      with:
        name: r
        path: 'r/*.tar.gz'
