name: build-kotlin

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: kotlin

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: kotlin

    - name: Run tests
      run: ./gradlew test
      working-directory: kotlin

    - name: Generate JAR
      run: ./gradlew jar
      working-directory: kotlin

    - name: Upload kotlin artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kotlin
        path: kotlin/build/libs/
