name: build-go

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: go/go.mod

    - name: Download dependencies
      run: go mod download
      working-directory: go

    - name: Check formatting
      run: |
        if [ -n "$(go fmt ./...)" ]; then
          echo "Code is not formatted. Please run 'go fmt ./...'"
          exit 1
        fi
      working-directory: go

    - name: Run tests
      run: go test -v ./...
      working-directory: go

    - name: Run tests with coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      working-directory: go

    - name: Build
      run: go build -v ./...
      working-directory: go

    - name: Upload go artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go
        path: go/
