name: build-pdf

on:
  workflow_call:
    inputs:
      release:
        description: 'Build in release mode'
        type: boolean
        default: false

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.0'

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        install-pandoc: true
        working-directory: pdf
        extra-packages: |
          any::rmarkdown

    - uses: r-lib/actions/setup-tinytex@v2
      env:
        TINYTEX_INSTALLER: TinyTeX-1
        TINYTEX_VERSION: 2025.06

    - name: Install additional LaTeX packages
      run: |
        tlmgr --version
        tlmgr update --self
        tlmgr install pgf caption textpos mdframed zref needspace csquotes multirow wrapfig colortbl pdflscape tabu varwidth threeparttable threeparttablex environ trimspaces ulem makecell biblatex logreq biber
        tlmgr list --only-installed

    - name: Download image artifacts
      uses: actions/download-artifact@v4
      with:
        name: img
        path: img/

    - name: Compose 'pdf'
      run: ./build.cmd pdf --only-compose ${{ inputs.release && '--release' || '' }}

    - name: Build 'pdf'
      run: ./pdf/build.sh ${{ inputs.release && '--release' || '' }}

    - name: Upload pdf artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: pdf/*.pdf
