name: build-rust

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: rust/pragmastat/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Check formatting
      run: cargo fmt -- --check
      working-directory: rust/pragmastat

    - name: Run clippy
      run: cargo clippy -- -D warnings
      working-directory: rust/pragmastat

    - name: Run tests
      run: cargo test --verbose
      working-directory: rust/pragmastat

    - name: Build release
      run: cargo build --release --verbose
      working-directory: rust/pragmastat

    - name: Package crate
      run: cargo package --verbose
      working-directory: rust/pragmastat

    - name: Upload rust artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust
        path: rust/pragmastat/target/package/*.crate
