name: build-python

on:
  workflow_call:
    inputs:
      publish:
        description: 'Publish to PyPI'
        type: boolean
        default: false

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest build twine
      working-directory: python

    - name: Install package in development mode
      run: pip install -e .
      working-directory: python

    - name: Run tests
      run: python -m pytest tests/ -v
      working-directory: python

    - name: Build package
      run: python -m build
      working-directory: python

    - name: Check package
      run: twine check dist/*
      working-directory: python

    - name: Upload python artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python
        path: python/dist/

    - name: Publish to PyPI
      if: ${{ inputs.publish }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: python/dist/
