name: build-web

on:
  workflow_call:
    inputs:
      release:
        description: 'Build in release mode'
        type: boolean
        default: false

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Download image artifacts
      uses: actions/download-artifact@v4
      with:
        name: img
        path: img/

    - name: Download pdf artifacts
      uses: actions/download-artifact@v4
      with:
        name: pdf
        path: pdf/

    - name: Build 'web'
      run: ./build.cmd web ${{ inputs.release && '--release' || '' }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: web/public
