name: release
run-name: "[release] ${{ github.ref_name }}"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # required for deploy-web

jobs:
  build-img:
    uses: ./.github/workflows/build-img.yml

  build-pdf:
    needs: build-img
    uses: ./.github/workflows/build-pdf.yml
    with:
      release: true

  build-web:
    needs: [build-img, build-pdf]
    uses: ./.github/workflows/build-web.yml
    with:
      release: true

  deploy-web:
    needs: build-web
    uses: ./.github/workflows/deploy-web.yml
    with:
      deploy_message: "Deploy: ${{ github.ref_name }}"

  build-python:
    uses: ./.github/workflows/build-python.yml

  publish-dotnet:
    uses: ./.github/workflows/build-dotnet.yml
    with:
      publish: true
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-python:
    runs-on: ubuntu-24.04
    needs: build-python
    permissions:
      id-token: write  # Required for trusted publishing to PyPI
    steps:
    - name: Download python artifacts
      uses: actions/download-artifact@v4
      with:
        name: python
        path: dist/

    - name: Remove platform-specific wheels
      run: rm -f dist/*.whl

    - name: Publish to PyPI (source distribution only)
      uses: pypa/gh-action-pypi-publish@release/v1
