title = 'Pragmastat: Pragmatic Statistical Toolkit'
baseURL = 'https://pragmastat.dev/'

languageCode = 'en-us'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['$', '$']]
  [markup.highlight]
    codeFences = true
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 5

[taxonomies]
  author = "authors"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
